### PR TITLE
support minify

### LINKED ISSUE #10: optimization of svg
I'm wondering if some optimization can be done on the svg to decrease the file size. For instance, I was thinking that maybe, instead of having a tag line for each character, it would be written so that you have a tagline for each word until the color changes.

So, instead of this:
```xml
    <text x="180px" y="16px" width="20px" height="32px" class='green bold'   >
        <tspan>n</tspan>
    </text>
    <text x="200px" y="16px" width="20px" height="32px" class='green bold'   >
        <tspan>a</tspan>
    </text>
    <text x="220px" y="16px" width="20px" height="32px" class='green bold'   >
        <tspan>m</tspan>
    </text>
    <text x="240px" y="16px" width="20px" height="32px" class='green bold'   >
        <tspan>e</tspan>
    </text>
```
It could be something like this:
```xml
    <text x="180px" y="16px" width="20px" height="32px" class='green bold'   >
        <tspan>name</tspan>
    </text>

```
I know literally nothing about writing svg files so it may not be possible. I was just looking for a way to make the file size smaller.

### PR DESCRIPTION
**Pull request by ahaoboy**
close: https://github.com/ahaoboy/ansi2/issues/10

```
-rw-r--r-- 1 ace None  77K Oct 23 17:04 win11.svg
-rw-r--r-- 1 ace None  35K Oct 23 17:04 nu-ls.svg
-rw-r--r-- 1 ace None  89K Oct 23 17:04 vitest.svg
```

```
-rw-r--r-- 1 ace None 8.5K Oct 23 17:13 win11.svg
-rw-r--r-- 1 ace None  15K Oct 23 17:13 nu-ls.svg
-rw-r--r-- 1 ace None  24K Oct 23 17:13 vitest.svg
```

image

```
 cr --features=cli --  -f=svg --font=https://fonts.cdnfonts.com/s/98875/JetBrainsMonoRegular.woff >  a.svg
```

image

### CODE REVIEW

**Comment by ahaoboy** [comment]
FiraCodeNerdFontMono-Regular.ttf

image

**Comment by fdncred** [comment]
Wow, this makes a huge difference. One small file went from 91.6kb to 38.3kb, then with -c went to 17.4kb. Nice work!

**Comment by ahaoboy** [comment]
> Wow, this makes a huge difference. One small file went from 91.6kb to 38.3kb, then with -c went to 17.4kb. Nice work!

However, due to SVG font rendering issues, you may need to use the mono font, otherwise it will cause alignment issues. This problem has not been found on HTML yet.

**Comment by ahaoboy** [comment]
> Wow, this makes a huge difference. One small file went from 91.6kb to 38.3kb, then with -c went to 17.4kb. Nice work!

If you are very concerned about the size, it is recommended to use html, which is much smaller than svg and will not have text rendering problems.

**Comment by fdncred** [comment]
What we're really trying to do is create a preview of all nushell themes and store them in a markdown file. I know md has limited html support, but I'll have to see what that is exactly. Our current idea is to put a svg in the markdown. I'm not sure how we'll get there from here because themes by their nature change all/most of the colors. 


It looks like some of the optimizations could make html even smaller. There are a lot of css colors in that file.

**Pull request merged**
